### ISSUE TITLE
BOXContentClient.accessTokenDelegate Can not be setted in 2.0.2

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#46] opened 2019-01-09 09:11 UTC
in the elder verison, I use BOXContentClient.default().authenticate() to call the func:
func fetchAccessToken(completion: ((String?, Date?, Error?) -> Void)!) in this func, I will return the accessToken and expiredDate to pass the authentication. But I found in v2.0.2 , the authenticate() didn't call this fetchAccessToken anymore. 
And I found that the accessTokenDelegate didn't has a setter. Only a getter in BOXContentClient.m : 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/23308747/50888779-61e71d00-1431-11e9-9b47-0c1f07ca3f63.png">

When debuging, I found that even if I call the delete func  , this var still nil .
<img width="929" alt="image" src="https://user-images.githubusercontent.com/23308747/50888867-88a55380-1431-11e9-8c93-70f133207dbc.png">
Is that a error for the BOX? Or how could I use appuser to present a box file?

**Comment by mattwiller** [comment] 2019-01-23 23:47
Closing as a duplicate of https://github.com/box/box-ios-sdk/issues/582 since the activity on this issue is located there.

**Closed by mattwiller** 2019-01-23 23:47 UTC
