### ISSUE TITLE
BOXFilePreviewController's default caching policy is changing.Shows "Not enough space"

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#49] opened 2019-02-11 09:37 UTC
when I use the BOXFilePreviewController to preview a box file, there's shows a blank window 
with "not enough space" 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/23308747/52554910-3d60d500-2e23-11e9-92e2-9f03955a0beb.png">
logging this entering box:
2019-02-11 16:18:26.009156+0800 SGMobile[9806:118304] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/xxx/Library/Developer/CoreSimulator/Devices/FE91D1DE-E14E-406D-8554-0812528AB3B1/data/Containers/Data/Application/8617ECB4-40BF-42BC-9F91-93D1026B2D7A/Library/Cookies/com.xxx.cio.be.soe.SolutionSeeker.binarycookies
exit the box window:
2019-02-11 16:28:45.979934+0800 SGMobile[9806:118304] DiskCookieStorage changing policy from 0 to 2, cookie file: file:///Users/xxx/Library/Developer/CoreSimulator/Devices/FE91D1DE-E14E-406D-8554-0812528AB3B1/data/Containers/Data/Application/8617ECB4-40BF-42BC-9F91-93D1026B2D7A/Library/Cookies/com.xxx.cio.be.soe.SolutionSeeker.binarycookies
How could I avoid this warning and make an correct preview?

**Comment by ManasaMS85** [comment] 2019-02-11 17:40
Yes even i am facing this issue - any solution for this, we have a release due and this is blocking the release

**Comment by ManasaMS85** [comment] 2019-02-11 19:13
The sample project also has the same issue - something to do with SDK.
<img width="455" alt="screen shot 2019-02-11 at 1 13 32 pm" src="https://user-images.githubusercontent.com/47312717/52587101-daf5dd80-2dfe-11e9-8036-bde1ee96a6f7.png">

2019-02-11 13:11:43.270008-0600 BoxPreviewSDKSampleApp[47966:469371] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/mmsaa/Library/Developer/CoreSimulator/Devices/FB715269-24D8-41D0-8B8E-0AF3118057A2/data/Containers/Data/Application/0605F541-67C6-4470-83C0-2F9B226CE840/Library/Cookies/com.box.ios.sampleapp.binarycookies

**Comment by mattwiller** [comment] 2019-02-12 01:15
@ManasaMS85 The issue you're seeing with the sample app (the `redirect_uri_mismatch` screen) is not related to the `DiskCookieStorage` logs — this screen appears because the sample app creates an SDK client using 3-legged OAuth2 authentication instead of Server-to-Server Auth (JWT Auth).  If you put the client ID/secret for a JWT Auth application into the sample app without any other modifications, it will not work as expected since these two authentication mechanisms are not compatible.  You'll either need to try the sample app with a client ID/secret from an OAuth2 application, or you may need to modify the sample application code to correctly instantiate the Server Auth client.

@wangqiwei66 I'm not sure if the logs you pasted in (the `DiskCookieStorage` ones) are related to the issue you're seeing or not.  Have you been able to try out the sample app to see if those logs appear there as well?  Note the above information about the different authentication types — you'll either need to try the sample app with a client ID/secret from an OAuth2 application, or you may need to modify the sample application code to correctly instantiate the Server Auth client.

**Comment by ManasaMS85** [comment] 2019-02-12 02:13
@mattwiller - But i see the similar issue as not enough storage on my integration as well

**Comment by wangqiwei66** [comment] 2019-02-12 02:19
@ManasaMS85 same issue. This error window is inside the boxViewController. when I clicked cancel, present the "Not Enough Space" window.

**Comment by ManasaMS85** [comment] 2019-02-12 19:02
@mattwiller  - attached is the screenshot i see when i preview an image 
<img width="463" alt="screen shot 2019-02-12 at 12 56 59 pm" src="https://user-images.githubusercontent.com/47312717/52660872-43f45880-2ec6-11e9-95e4-4885ef458ffa.png">

The logs are : 
2019-02-12 12:58:09.847904-0600 -[AppDelegate application:supportedInterfaceOrientationsForWindow:] NO Rotate
2019-02-12 12:58:09.857867-0600 The behavior of the UICollectionViewFlowLayout is not defined because:
2019-02-12 12:58:09.858012-0600 the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2019-02-12 12:58:09.858230-0600 The relevant UICollectionViewFlowLayout instance is <BOXPreviewCollectionViewFlowLayout: 0x7fb5c7f54580>, and it is attached to <UICollectionView: 0x7fb5c934fe00; frame = (0 0; 414 896); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600002fdce70>; layer = <CALayer: 0x6000021f8320>; contentOffset: {0, -88}; contentSize: {0, 0}; adjustedContentInset: {88, 0, 34, 0}> collection view layout: <BOXPreviewCollectionViewFlowLayout: 0x7fb5c7f54580>.
2019-02-12 12:58:09.858348-0600 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
2019-02-12 12:58:09.861759-0600 The behavior of the UICollectionViewFlowLayout is not defined because:
2019-02-12 12:58:09.861868-0600 the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2019-02-12 12:58:09.862018-0600 The relevant UICollectionViewFlowLayout instance is <BOXPreviewCollectionViewFlowLayout: 0x7fb5c7f54580>, and it is attached to <UICollectionView: 0x7fb5c934fe00; frame = (0 0; 414 896); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600002fdce70>; layer = <CALayer: 0x6000021f8320>; contentOffset: {0, -88}; contentSize: {414, 774}; adjustedContentInset: {88, 0, 34, 0}> collection view layout: <BOXPreviewCollectionViewFlowLayout: 0x7fb5c7f54580>.
2019-02-12 12:58:09.862119-0600 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
unknown
2019-02-12 12:58:10.428021-0600  [] nw_proxy_resolver_create_parsed_array PAC evaluation error: NSURLErrorDomain: -1003
2019-02-12 13:00:01.434613-0600  [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C97.1.1:2][0x7fb5c7ce8900] get output frames failed, state 8196
2019-02-12 13:00:01.434832-0600  [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C97.1.1:2][0x7fb5c7ce8900] get output frames failed, state 8196
2019-02-12 13:00:01.435250-0600  TIC Read Status [97:0x0]: 1:57
2019-02-12 13:00:01.435364-0600  TIC Read Status [97:0x0]: 1:57
2019-02-12 13:00:02.613897-0600  TIC Read Status [98:0x6000015598c0]: 1:57
2019-02-12 13:00:02.614145-0600  TIC Read Status [98:0x6000015598c0]: 1:57
2019-02-12 13:00:02.614339-0600  TIC Read Status [98:0x6000015598c0]: 1:57
2019-02-12 13:00:02.627484-0600  [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C98.1.1:2][0x7fb5ca21f180] get output frames failed, state 8196
2019-02-12 13:00:02.627621-0600  [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C98.1.1:2][0x7fb5ca21f180] get output frames failed, state 8196
2019-02-12 13:00:02.628047-0600  TIC Read Status [98:0x0]: 1:57
2019-02-12 13:00:02.628161-0600  TIC Read Status [98:0x0]: 1:57
2019-02-12 13:00:02.628276-0600  TIC Read Status [98:0x0]: 1:57
2019-02-12 13:00:02.628456-0600  TIC Read Status [98:0x0]: 1:57
2019-02-12 13:00:10.377221-0600  Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2019-02-12 13:00:10.377752-0600  Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery

**Comment by mattwiller** [comment] 2019-02-12 19:28
@wangqiwei66 @ManasaMS85 Looking through the Preview SDK code, it looks like the "Not Enough Space" error message might be triggered by not having enough space on the device to store the preview representation of the file you're attempting to view.  Could you check a few things for me so we can continue troubleshooting?

1. How large are the files you're trying to preview when you see the "Not Enough Space" error?
2. How much disk space is left on the device you're testing on?
3. Are you seeing this error on an actual device or in the simulator?
4. If none of the above seem to provide useful information, could you email the API key/client ID you're using to sdks@box.com so we can look in our server logs to see if anything is going wrong on the API side?

**Comment by ManasaMS85** [comment] 2019-02-12 22:57
@mattwiller  - Answers for your below questions 
*how large are the files you're trying to preview when you see the "Not Enough Space" error? - this error i see consistently for all images irrespective of size
* How much disk space is left on the device you're testing on? - Device has 30 Gb space left, so it cannot be device issue 
* Are you seeing this error on an actual device or in the simulator? - We are seeing the error in both simulator and Device 
* . If none of the above seem to provide useful information, could you email the API key/client ID you're using to [sdks@box.com](mailto:sdks@box.com) so we can look in our server logs to see if anything is going wrong on the API side?  - Sure will send the AOU key/Client ID

**Comment by wangqiwei66** [comment] 2019-02-13 02:40
@mattwiller - Answers for your below questions
*how large are the files you're trying to preview when you see the "Not Enough Space" error? - this error i see consistently for all images irrespective of size
   How large are the files you're trying to preview when you see the "Not Enough Space" error? **The previewing file size is 198.1746KB.**
    How much disk space is left on the device you're testing on? - **Device has 79.17 Gb space left.**
    Are you seeing this error on an actual device or in the simulator? - **We are seeing the error in both simulator and Device**

**Comment by ManasaMS85** [comment] 2019-02-13 04:08
@mattwiller - Few scenarios to be explained here . 
1. The use case "Unable to load image" comes only on first launch of the simulator or device. Suspend the app and retry - it works 
2. When we try to see the difference on second launch and first launch 
---- The app sandbox doesnot create a "Boxpreview" folder on the first launch at all . But very same thing on second launch - we see that "boxpreview" folder is created and cache has the image as well
3. We tried to track the requests which goes via simulator in charles. 
<img width="1504" alt="screen shot 2019-02-12 at 5 59 10 pm" src="https://user-images.githubusercontent.com/47312717/52686169-1e8d3c00-2f12-11e9-9133-0bdf075581d1.png">
This is the request image which goes via charles - when a box preview is called - Second launch of simulator
<img width="1500" alt="screen shot 2019-02-12 at 9 59 20 pm" src="https://user-images.githubusercontent.com/47312717/52686189-3fee2800-2f12-11e9-9c36-d1bf9ee47a3a.png">
This is the request image which goes via charles - when a box preview is called - on first launch of simulator - 
If you see here the requests only are not going out of SDK . Everything remains same . Both the cases first i am fetching the boxfile from box.com - which is successful. 

This is some thing do with BoxPreview SDK when used with "ServerAuthUser" kind authentication 
box-ios-sdk version : 2.2.0
box-ios-preview-sdk version: 2.1.2
iOS version: iOS12 and iOS11

**Comment by ManasaMS85** [comment] 2019-02-14 06:56
@mattwiller - Any response on this issue - i have a release - could you please help us trouble shoot the same

**Comment by ManasaMS85** [comment] 2019-02-20 21:20
@mattwiller  - Please find attached sample code - to reproduce the"**Unable to load image**" Issue . 
The steps to reproduce is : 
Click Logout
Click Login
Click Preview Image
[BoxTest.zip](https://github.com/box/box-ios-preview-sdk/files/2886534/BoxTest.zip)

Before running the project 
1. Uopdate the cartfile
2. Update the accesstoken - which is valid

**Comment by mattwiller** [comment] 2019-02-21 07:46
@ManasaMS85 The issue described in the sample app you sent doesn't seem to be the issue that this thread is about — if you have a code sample that reproduces the "Not enough space" error, please let us know.

**Comment by ManasaMS85** [comment] 2019-02-21 15:04
@mattwiller  - Hey Matt "**Unable to load image**" comes for image and if you have a pdf, xls or word - "Not enough space" comesup

**Comment by mattwiller** [comment] 2019-02-21 19:12
@ManasaMS85 Ah, I see — thanks for clarifying.  I'm able to reproduce the "Not enough space" issue as well.  I think the solution for this should be the same as for the other related issue — does re-creating the client for each new session solve this as well?

**Comment by ManasaMS85** [comment] 2019-02-22 02:32
@mattwiller - Yes it does for this as well

**Comment by mattwiller** [comment] 2019-02-22 19:11
Since this issue is confirmed as the same root cause as https://github.com/box/box-ios-sdk/issues/593 I'm going to close this one for now.  We can continue discussion on that issue.

**Closed by mattwiller** 2019-02-22 19:11 UTC
